### ISSUE TITLE
Let's Encrypt certificates not created

### ISSUE THREAD

**Issue by shaneonabike** [omega8cc/hosting_le#11]
After enabling everything it would appear that the certificates are being created, but when I visit the website  in SSL I am told that it is not a valid certificate. Meaning, it's not actually a Let's Encrypt certificate.

Any ideas I could verify or debug this?

**Comment by omega8cc** [comment]
Please check the task log lines with [hosting_le] prefix and expand them to read complete output. It should contain detailed diagnosis of the situation and information what to do next.

**Comment by shaneonabike** [comment]
Yeah after verifying the site again and the platform that seemed to resolve the issue of it providing an invalid certificate. I ended up having to remove this since the module (or Aegir at least) was taking over all my certificate declerations for other sites on the same server :/
