### ISSUE TITLE
Allow using for the hostmaster site

### ISSUE THREAD

**Issue by helmo** [omega8cc/hosting_le#2]
There was a specific check to skip the hostmaster site for LE certificates.

I've hacked it a bit to make it functional, but in the process broke my test site .. so handle with care. This needs more testing ;)

My WIP is in https://github.com/helmo/hosting_le/tree/feature/hostmaster-ssl

**Comment by omega8cc** [comment]
It is a dangerous idea to enable it (at least without limiting it to hostmaster upgrade), so in BOA we have created separate procedure to add LE cert to hostmaster outside of it, and only once it is already created, so it works only on upgrade.

The reason it shouldn't be used on initial install is that the code will be triggered too early in the process, there will be no SSL feature enabled yet, and before the initial verify tasks will run to properly write all drush aliases.

There is just no way to make it work, unless you will add/enable nginx_ssl or apache_ssl in the makefile and you will fire hosting-dispatch a few times internally first.

**Comment by helmo** [comment]
Just for documentation purposes, I've tried it on another server with success.
- Have a fully functional, verified site. Log in via http.
- Enable apache_ssl on the server node( e.g. /hosting/c/server_master)
- Enable the hosting features, Hosting LE Vhost and Hosting LE SSL 
- Edit the hostmaster site node to set SSL to 'Enabled' (NOT to required, you can do that later.
- Fill the 'New encryption key' field with the uri of your site, e.g. aegir.example.com
- Let the verify task finish
- You have to re-login

@omega8cc I agree that it's not something to enable by default.

**Comment by omega8cc** [comment]
I have merged in this change: https://github.com/omega8cc/hosting_le/commit/58990c40e2a0bb4a046c4025d17ab5082dbb7d73

Readme update: https://github.com/omega8cc/hosting_le/commit/122358bf4b7077cf7abfd5daae9b7d8d9fad0c66

Thanks!
