### ISSUE TITLE
Support remote sites

### ISSUE THREAD

**Issue by helmo** [omega8cc/hosting_le#3]
Another WIP in https://github.com/helmo/hosting_le/tree/feature/remote-server

Answering the challenge works via a hook in letsencrypt.sh

It sometimes works... Setting $force_renew = TRUE is needed otherwise the good certs are overridden again with selfsigned ones.

**Comment by helmo** [comment]
It now seems to work reliably after commit 2f57cff87832ed6f1d227f2eeeab706bb986dbe8

Only a few warning remain about unlinking old files that don't exist... which could probably be fixed with an @ prefix.

@omega8cc, @gboudrias please review.

**Comment by omega8cc** [comment]
Hey @helmo, @gboudrias -- we have added you both to this project. Please commit any improvements you will find useful. Thanks!

**Comment by omega8cc** [comment]
@helmo -- It shouldn't hardcode `/var/aegir/` path, and the feature should be optional. Not everyone needs it, by default.

**Comment by helmo** [comment]
Good point about hardcoding /var/aegir ... now removed.
We do have quite a few more of those though ... core contrib and boa.

Not sure what you mean by 'the feature should be optional'... this code does not interfere on a singe server setup.

**Comment by omega8cc** [comment]
Thank you for the hardcoded path fix.

I mean things like:

```
    if (!provision_file()->exists($le_hook)->status()) {
      drush_log('[hosting_le] Please copy letsencrypt-sh-hooks.sh to ' . $le_root, 'warning');
      return FALSE;
    }
```

```
$le_options = '--cron --hook ' . $le_hook;
```

This introduces requirement which is not backward compatible, so it breaks existing instances, until the `letsencrypt-sh-hooks.sh` file is copied to the expected location.

This should be made optional, and not required, also because it is not needed on single-system Aegir instances.

**Comment by omega8cc** [comment]
Note that BOA specific checks in this extension only modify the extension behaviour if BOA is detected, but otherwise don't affect vanilla Aegir installations (unless I have missed something?)

**Comment by omega8cc** [comment]
So we should have something like this instead:

```
if (provision_file()->exists($le_hook)->status()) {
  $le_options = '--cron --hook ' . $le_hook;
}
else {
  $le_options = '--cron';
  drush_log('[hosting_le] To support remote sites please copy letsencrypt-sh-hooks.sh to ' . $le_root, 'info');
}
```

**Comment by helmo** [comment]
I'll look into that. Might be even nicer to detect if the site is on a remote server.

**Comment by helmo** [comment]
One extra commit added to the PR  ... https://github.com/omega8cc/hosting_le/pull/4/commits/140fd571104c538310f346c65e4a229ab263bccf

That should detect if it's on a remote server.

**Comment by omega8cc** [comment]
Committed. Thanks!
