### ISSUE TITLE
Can't enable ssl

### ISSUE THREAD

**Issue by serhatozkara** [omega8cc/hosting_le#6]
When I try to enable ssl through edit page of a site, I get this error:
"The encryption key field is required to enable us to generate a new SSL certificate for your site." thus, i cant enable https for the site. Is there any workaround?

**Comment by helmo** [comment]
You should be able to see a 'New encryption key' text field a bit lower
on that same form...
You need to give a name there, just use the site node's title.

**Comment by serhatozkara** [comment]
Yes, but those fields are not shown on the browser. Some div classes like: "class="form-item form-type-radios form-item-ssl-key" are display:none default but when i select SSL enabled it changes to: display:block but even then these divs are not shown on the UI. tried different browsers. Screenshot attached
<img width="1280" alt="screen shot 2016-07-28 at 11 43 44 am" src="https://cloud.githubusercontent.com/assets/3116157/17206610/491c60c6-54b9-11e6-8556-42d603ca597d.png">

**Comment by omega8cc** [comment]
@serhatozkara -- You seem to use BOA, so please post this issue in the BOA queue. In BOA we hide this field and it's automatically filled with site name. If it doesn't work for you for some reason, it needs to be posted at https://github.com/omega8cc/boa/issues
