### ISSUE TITLE
Create a d.o project

### ISSUE THREAD

**Issue by jkenn99** [omega8cc/hosting_le#8]
It would be nice to have this on drupal.org so that it can be installed using drush.

**Comment by omega8cc** [comment]
It already exists: https://www.drupal.org/project/hosting_le

**Comment by omega8cc** [comment]
We have just posted [dev and stable releases on d.o](https://www.drupal.org/project/hosting_le/releases)

**Comment by jkenn99** [comment]
Thanks!
